name: Update Common Workflow

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-common:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup git remote for template
        run: |
          git remote add nagiyu https://github.com/nagiyu/nagiyu-aws-serverless-template.git
          git fetch nagiyu master

      - name: Merge template master branch
        run: |
          git merge nagiyu/master --allow-unrelated-histories -m "Merge template master branch"

      - name: Push changes
        run: |
          git push origin HEAD:refs/heads/main
